### ISSUE TITLE
onNavigationEvent() bundle needs URL value

### ISSUE THREAD

**Issue by sakuraso13** [GoogleChrome/android-browser-helper#115]
Currently `Bundle` in `onNavigationEvent()` sends us `timestampUptimeMillis` value. But it seems to me it would not be superfluous to send a link to the site at which an event occurred as in a webview.

**Comment by PEConn** [comment]
onNavigationEvent is something that TWAs share with Custom Tabs. The reason it doesn't have a URL when used for Custom Tabs is that the user shares state (eg login status) with Chrome and providing the URL could leak user data.

We could allow the URL to be included for a TWA when the user is on the verified origin - however from your point of view, you could probably get the information you want from logging from the webpage.

**Comment by andreban** [comment]
@sakuraso13 the bundle is filled by the browser itself and there's nothing `android-browser-helper` can do there. I'd recommend filing this as a feature-request at bugs.chromium.org if that's indeed needed.  Closing the issue here.
