### ISSUE TITLE
Status bar is not hiding with immersive display mode

### ISSUE THREAD

**Issue by nishtrack** [GoogleChrome/android-browser-helper#124]
**Describe the bug**
I am working on a display mode feature which added a few months back ago. I updated the android-browser-helper library to 1.3.1 and added snippet code in the manifest. I was expecting to my app should go in full-screen mode as we get in PWA while setting the display mode to fullscreen but nothing happens, the status bar was still showing with lots of attempts

**To Reproduce**
Same behavior I am getting even with demo example(basic-twa) in this repository

**Expected behavior**
Status bar should be hide

**Code Snippets**
  `<meta-data android:name="android.support.customtabs.trusted.DISPLAY_MODE"
                android:value="immersive"/>`

**Smartphone (please complete the following information):**
 - Device: Xiomi redmi 4
 - OS: Android 7
 - Browsers Installed: Chrome
 - Browser Versions 76
 - android-browser-helper library version 1.3.1

**Comment by andreban** [comment]
It seems you are using Chrome 76. Can you check with a current version of Chrome?

**Comment by andreban** [comment]
Closing this, as immersive mode was not supported on Chrome 76. Please, re-open this is reproducible on a current Chrome version.

**Comment by nishtrack** [comment]
Thanks for responding. Yes, It is now working with the latest version of chrome. which minimum chrome version is required for Immersive mode?
