### ISSUE TITLE
Here are two doubts that I hope will be solved

### ISSUE THREAD

**Issue by SmallRedSister** [GoogleChrome/android-browser-helper#125]
Hello! I am very honored to know this technology and believe that it will be brilliant in the future. Now I am trying to learn some of these technologies and use them in actual combat. However, I have encountered two very big problems. I hope you can help me. Thank you very much!

1. I'm a Chinese developer. In China, we can't use the Google service normally. I wonder, can we replace the search engine with something else? For example, replace it with Baidu.

2. I don't know if you have considered such a problem, which is very common in our side. When the page I loaded has the login function and supports the third-party authorized login, will it be handled like a browser? For example, it won't be transferred from my current app to other browsers on my phone to complete the task. We need all operations to be done on the app we developed.

**Comment by andreban** [comment]
> I'm a Chinese developer. In China, we can't use the Google service normally. I wonder, can we replace the search engine with something else? For example, replace it with Baidu.

Trusted Web Activity is a browser feature and a protocol based on Android Intents and Services. This means other browsers,  can add support for it. Firefox and Edge already do.

> I don't know if you have considered such a problem, which is very common in our side. When the page I loaded has the login function and supports the third-party authorized login, will it be handled like a browser? For example, it won't be transferred from my current app to other browsers on my phone to complete the task. We need all operations to be done on the app we developed.

Not sure if this answer your questions, but when navigating outside the initial origin (eg: your app), the navigation will be handled in a [Custom Tab](https://developers.google.com/web/android/custom-tabs).

**Comment by SmallRedSister** [comment]
Looking forward to Chinese developer documentation

**Comment by SmallRedSister** [comment]
The browser is a search engine to choose from, which is what I care about.

**Comment by andreban** [comment]
Closing this as the question has been answered.
