### ISSUE TITLE
ANR - Input dispatching timed out (Waiting because the touched window is paused.)

### ISSUE THREAD

**Issue by rockeynebhwani** [GoogleChrome/android-browser-helper#143]
We are on v1.3.1 of android-browser-helper and saw a new error recently (only 1 occurrence so far)

![image](https://user-images.githubusercontent.com/1718757/89024147-8f016600-d31c-11ea-8994-c86f36dbf7f4.png)

![image](https://user-images.githubusercontent.com/1718757/89024123-8577fe00-d31c-11ea-8719-c1ee5b118c7b.png)

**Comment by andreban** [comment]
Closing this, as it seems we're not getting further reports on this issue.
