### ISSUE TITLE
Crashlytics Error - UiAutomatorInteractionController.java line 39

### ISSUE THREAD

**Issue by rockeynebhwani** [GoogleChrome/android-browser-helper#144]
We are on v1.3.1 for android-browser-helper and seeing this error in Crashlytics. Let me know if you need any more information from my side to investigate this. 

![image](https://user-images.githubusercontent.com/1718757/89024789-95441200-d31d-11ea-8852-f68877c5ffde.png)

**Comment by andreban** [comment]
This crash is happens in UiAutomatorInteractionController. This is neither part of or used by androidx.browser and android-browser-helper.  The stack trace does point to `androidx.test.runner.AndroidJUnitRunner`, which seems to indicate indicate the test suite for the application crashing - a lab crash, not the device crashing with end users, and issue with test configuration, not the libraries. Closing as this is outside the scope of this repository.
