### ISSUE TITLE
Crashlytics Error - SQLiteConnection.java - The database file is locked. (database is locked (code 5): , while compiling: PRAGMA journal_mode) 

### ISSUE THREAD

**Issue by rockeynebhwani** [GoogleChrome/android-browser-helper#145]
We are on v1.3.1 of android-browser-helper and saw this error in Crashlytics. Please let me know if you need any more information form our side to investigate this. We don't know steps to re-produce

![image](https://user-images.githubusercontent.com/1718757/89025395-ae998e00-d31e-11ea-9468-7c5e1276896b.png)

**Comment by andreban** [comment]
@rockeynebhwani this doesn't look like an issue with Trusted Web Activity or android-browser-helper: `androidx.browser` and `android-browser-helper` don't make use of local databases. This particular crash seems to come from [this class on the the Firebase SDK](https://github.com/firebase/firebase-android-sdk/blob/59db5902f1236f44f2b6aaadb632b6db2e32a3ef/transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/persistence/SQLiteEventStore.java.). I'm closing the issue as it's outside the scope of this repository.

**Comment by rockeynebhwani** [comment]
Thanks @andreban. Link you provided in your comment is giving 404. Can you please check and share correct link?

**Comment by andreban** [comment]
Fixed. Had an extra `.` at the end of URL.
