### ISSUE TITLE
App icon default to android icon

### ISSUE THREAD

**Issue by Vegas10128** [GoogleChrome/android-browser-helper#171]
After configuring twa application and adding IC Launch icons to the project. I run android emulator and install the app to my phone. Custom Icons do not appear after install only defaulting to android IC_launch icons.

**Comment by andreban** [comment]
@Vegas10128 How did you configure the application? The library doesn't generate or change any icons in the app, and defining icons and referencing them on AndroidManifest.xml should work as expected.

**Comment by Vegas10128** [comment]
Hello andreban!
So sorry for the immediate bug report, 
I did discover that the icon was not presented in the manifest xml file so i went ahead and added the code to it and resolved my issue.

**Comment by andreban** [comment]
Cool. Closing the issue then.
