### ISSUE TITLE
Not responding and logout without announcement.

### ISSUE THREAD

**Issue by Kapp1** [GoogleChrome/android-browser-helper#174]
Last login: Mon Sep 14 06:34:44 on ttys000
kapp1@kapp1 ~ % /Applications/Google\ Chrome.app/Contents/mac/Google\ Chrome ; exit;
[0914/063600.029151:WARNING:process_memory_mac.cc(93)] mach_vm_read(0x7ffeefa21000, 0x2000): (os/kern) invalid address (1)
[0914/063600.161198:WARNING:crash_report_exception_handler.cc(240)] UniversalExceptionRaise: (os/kern) failure (5)
zsh: segmentation fault  /Applications/Google\ Chrome.app/Contents/mac/Google\ Chrome
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

**Comment by andreban** [comment]
It seems this issue is referencing Chrome for MacOS. This library only works with Android browser. https://bugs.chromium.org/ is likely the right place for this bug. Closing it as it's outside the scope of this repo.

**Comment by Kapp1** [comment]
aha sorry and thank you 👍🏻
