### ISSUE TITLE
assetlinks verification fails for a path

### ISSUE THREAD

**Issue by jitendra1607** [GoogleChrome/android-browser-helper#182]
**If PWA is served at subdomain.example.com then assetlinks getting verified successfully and no URL shown in TWA.**

`<string name="asset_statements">
        [{
            \"relation\": [\"delegate_permission/common.handle_all_urls\"],
            \"target\": {
                \"namespace\": \"web\",
                \"site\": \"https://subdomain.example.com\"}
        }]
    </string>`

`<meta-data android:name="android.support.customtabs.trusted.DEFAULT_URL"
                android:value="subdomain.example.com" />`

**but if PWA is served at subdomain.example.com/client1 then assetlinks not verifying and the URL is shown in TWA.**

`<string name="asset_statements">
        [{
            \"relation\": [\"delegate_permission/common.handle_all_urls\"],
            \"target\": {
                \"namespace\": \"web\",
                \"site\": \"https://subdomain.example.com/client1\"}
        }]
    </string>`

`<meta-data android:name="android.support.customtabs.trusted.DEFAULT_URL"
                android:value="subdomain.example.com/client1" />`

Please suggest what is the best way to serve different TWA from single domain(like subdomain.example.com)?

**Comment by jitendra1607** [comment]
I think that site url below is ineffective for path because app is still looking for assetslinks.json at "subdomain.example.com" instead of "subdomain.example.com/client1". As a result URL hidden only if I serve assetlinks.json on "subdomain.example.com"  from server, serving assetlinks.json on "subdomain.example.com/client1" is not effective. 

`<string name="asset_statements"> [{ \"relation\": [\"delegate_permission/common.handle_all_urls\"], \"target\": { \"namespace\": \"web\", \"site\": \"https://subdomain.example.com/client1\"} }] </string>`

**Please suggest what should be done.**

**Comment by jitendra1607** [comment]
@andreban help please

**Comment by andreban** [comment]
@jitendra1607 Digital Asset Links validates and **origin** agains and Android app.  An app can be validated against multiple origins, and an origin can have multiple apps, which is what you are looking for in this case.

In summary
 1. `https://subdomain.example.com/.well-known/assetlinks.json` will contain references to both apps.
 2. Each app will contain an `asset_statement` that connects it to `https://subdomain.example.com`. 
 3. Each app will have different launch URLs.

Let me know if this helps.

**Comment by jitendra1607** [comment]
@andreban Yes i am aware of what you said but in this case I have serve apps from different subdomains like `https://clent1.example.com` and `https://clent2.example.com` so on. I was looking for the possibility of `https://subdomain.example.com/cleint1` and `https://subdomain.example.com/client2` so on. 
**Is it possible?** please show me some code also if possible.

**Comment by jitendra1607** [comment]
@andreban @PEConn
How to generate 'assetslinks.json' dynamically if i have thousands of PWA (pwa1, pwa2 .... so on). Can I add query param or path variable to the request(initiated from android for verification) to decide the respective 'assetslinks.json' to be served from the server?

**Comment by andreban** [comment]
To my knowledge, it's not possible to generate Digital Asset Links dynamically, as they have to be statically created in the Android app.
