### ISSUE TITLE
Small splash screen icon after androidbrowserhelper:2.0.0 upgrade

### ISSUE THREAD

**Issue by jitendra1607** [GoogleChrome/android-browser-helper#184]
`    implementation 'com.google.androidbrowserhelper:androidbrowserhelper:2.0.0'
`

I noticed that splash screen icon is very small now after upgrading to 'com.google.androidbrowserhelper:androidbrowserhelper:2.0.0'

Please suggest how to increase icon size?

**Comment by andreban** [comment]
Could you post a screenshot of the splash screen? IIRC, the library passes the icon to Chrome as-is, and shouldn't have any effect on the icon size. @PEConn can confirm.

**Comment by jitendra1607** [comment]
@andreban  
After upgrade the below screenshot

[![Whats-App-Image-2020-09-23-at-16-45-34.jpg](https://i.postimg.cc/TP74RRgV/Whats-App-Image-2020-09-23-at-16-45-34.jpg)](https://postimg.cc/p9jZCM0r)

Before upgrade below screenshot

[![Whats-App-Image-2020-09-23-at-16-45-45.jpg](https://i.postimg.cc/0jpnJxMH/Whats-App-Image-2020-09-23-at-16-45-45.jpg)](https://postimg.cc/n9hB6y1v)

**Comment by andreban** [comment]
Closing this, as android-browser-helper doesn't generate icons. If you used Bubblewrap, could you open an issue at https://github.com/GoogleChromeLabs/bubblewrap?
