### ISSUE TITLE
Add 'TrustedWebActivityIntentBuilder.setShowTitle'

### ISSUE THREAD

**Issue by vladk1** [GoogleChrome/android-browser-helper#203]
`TrustedWebActivityIntentBuilder` already allows toolbar color customisation via `setToolbarColor`.
Would it be possible to also configure if the title should be displayed in the toolbar?
https://developer.android.com/reference/androidx/browser/customtabs/CustomTabsIntent.Builder#setShowTitle(boolean)

**Describe the solution you'd like**
I would imagine simply adding
```
    @NonNull
    public TrustedWebActivityIntentBuilder setShowTitle(boolean showTitle) {
        mIntentBuilder.setShowTitle(showTitle);
        return this;
    }
```
into `TrustedWebActivityIntentBuilder` would allow it?

**Comment by PEConn** [comment]
We can look into doing this, but why would we want it?

The title wouldn't be shown while on the TWA's domain (since the entire top bar is hidden then), it would only be applicable when the user navigates off origin.

**Comment by vladk1** [comment]
Yes, it would be useful for the scenario when we do not setup Digital Asset Link or if we fallback to custom tab and we want to display the title in addition to url.
I guess it shouldn't be difficult to support given that color customisation via `setToolbarColor` is already exists for the same scenario?

**Comment by PEConn** [comment]
If you're not going to set up Digital Asset Links, then why not just launch the website as a Custom Tab which already has setShowTitle?

**Comment by vladk1** [comment]
It seemed easier to do it via "android-browser-helper" (as shown in [twa-webview-fallback demo](https://github.com/GoogleChrome/android-browser-helper/tree/master/demos/twa-webview-fallback)) so that we can re-use implemented logic (for service connection and fallbacks).
I looked at the [customtabs demo](https://github.com/GoogleChrome/android-browser-helper/tree/master/demos/custom-tabs-example-app/src/main/java/org/chromium/customtabsdemos) and looks like it would require more work for a simple use case to display external webpage?

**Comment by PEConn** [comment]
Custom Tabs should definitely be easier to use than Trusted Web Activities, although yeah, we've not put as much effort into making convenience methods/templates. The Custom Tabs demo is pretty complex (I think it covers each and every feature in Custom Tabs).

So you just want a simple app that starts up and launches a Custom Tab to a web page?

**Comment by PEConn** [comment]
@andreban for thoughts on making demos/documentation for Custom Tabs easier.

**Comment by vladk1** [comment]
> So you just want a simple app that starts up and launches a Custom Tab to a web page?

Yes. 
Is there a similar component like `com.google.androidbrowserhelper.trusted.LauncherActivity` to launch Custom Tab and with logic to have WebView fallback?

If we decide to use Trusted Web Activity that allows Digital Asset Link, it could still be nice to expose customisation methods to display toolbar correctly when we have to fallback to custom tab?

**Comment by PEConn** [comment]
The main reason I ask is that something being launched as a TWA but having the Digital Asset Links fail to verify counts as a failure, and at some point Chrome may change its behaviour to be less forgiving when that happens. (It will always be fine for a TWA to navigate off the verified origin and show the CCT UI, but failing verification is a failure.)

Having a `setShowTitle` method on `TrustedWebActivityIntentBuilder` wouldn't be too difficult, but it would take at least two months to roll out through the AndroidX release process and I'd want evidence of a wider need for that method.

Creating a `CustomTabsLauncherActivity` in Android Browser Helper has a less high bar and I'd be happy to do that if I get some spare time (@andreban in case you have some). It looks relatively simple, doing something like:

```

TwaProviderPicker.Action action =
    TwaProviderPicker.pickProvider(context.getPackageManager);
if (action.launchMode == LaunchMode.BROWSER) {
  // WebView fallback
  // Assuming that `this` is an Activity.
  startActivity(WebViewFallbackActivity.createLaunchIntent(
    this, url, LauncherActivityMetadata.parse(this)));
} else {
  // Launch Custom Tab
  CustomTabsIntent.Builder builder = new CustomTabsIntent.Builder();
  CustomTabsIntent customTabsIntent = builder.build();
  customTabsIntent.launchUrl(this, Uri.parse(url));
}
```

**Comment by andreban** [comment]
You can extend the existing `LauncherActivity` and provide your own fallback strategy for the Trusted Web Activity:

```java /1-4
public class CustomLauncherActivity extends LauncherActivity {
    @Override
    protected TwaLauncher.FallbackStrategy getFallbackStrategy() {
        return (context, twaBuilder, providerPackage, completionCallback) -> {
            CustomTabsIntent intent = new CustomTabsIntent.Builder()
                    .setShowTitle(false)
                    .build();

            if (providerPackage != null) {
                intent.intent.setPackage(providerPackage);
            }

            intent.launchUrl(context, twaBuilder.getUri());
            if (completionCallback != null) {
                completionCallback.run();
            }
        };
    }
}
```
