### ISSUE TITLE
Add browse history to user browse history

### ISSUE THREAD

**Issue by DHosseiny** [GoogleChrome/android-browser-helper#205]
I don't want to open a URL for the user. In my app, I just want to add some URL to my user browsing history. I want to explain my use-case. For example, my user goes through this deep link in my app: "myApp://productId=3"
And the same page on my website is "www.mysite.com/productId=3". But I want when my user browses my application, it's browsing history copies to chrome history and the user can see my app history between his web browsing history. So when my user opens that Deeplink I want to add "www.mysite.com/productId=3" to his browse history for better UX. Even if using this library is can not do anything with my Idea please guide me. I asked this [here](https://stackoverflow.com/questions/64662065/add-a-web-url-to-user-web-browsing-history-form-android-application) too. Thanks in regard.

**Comment by PEConn** [comment]
So to be clear, which of the following do you want to do:

1. Have a web page be added to the user's browsing history *without* actually opening a new Activity.
2. Open a web page as a Custom Tab and have that added to the user's browsing history.
3. Open a web page as a Trusted Web Activity and have that added to the user's browsing history.

**Comment by andreban** [comment]
Closing this as inactive
