### ISSUE TITLE
How to call TWA native method from Java Script running in url

### ISSUE THREAD

**Issue by mohit1993** [GoogleChrome/android-browser-helper#230]
I am unable to find any method like webview.addJavascriptInterface in TWA , please let me know if this is possible.

**Comment by PEConn** [comment]
Hey, currently this is not possible.

There are discussions about adding postMessage support to TWAs - this would allow the Android app and the website to communicate with each other, and would effectively do what you're trying to do. At the moment though, we're gathering the user cases we have for this.

We already have a discussion going on Issue #55 , so do you mind adding your use case to that thread? I'm going to close this issue in favour of that one.
