### ISSUE TITLE
Sign out from TWA with custom auth

### ISSUE THREAD

**Issue by mohit1993** [GoogleChrome/android-browser-helper#236]
I am launching a web url from My TWA native app, my native code only has one activity, no service at all.
I am doing authentication on native side and putting token into shared preferences(browser) which web code uses for authentication. Now i need to add functionality to sign out, sign out button is on web ui. So I need to invoke few line of codes to sign out on native side when sign out event occurs on web.
I can see in document that it can be possible with Intent uri's but there is only activity invoking example, which is not fit to my use case. I wonder if a broadcast can also be sent to my native from web so that i can execute some code or any alternative to this problem in TWA.

**Comment by andreban** [comment]
It sounds to me you will need to start a native Activity to handle this (even if it's an Activity that doesn't have UI and closes itself after the sign-out.

Another question, if the app only has one native Activity, is that the LauncherActivity? If that's the case, why not handling sign-in entirely in the web app?

**Comment by mohit1993** [comment]
1. I am trying this but intent is not launching activity from native.
window.open('intent://scan/#Intent;scheme=zxing;package=xxx;S.browser_fallback_url=http//google.com;end', '_self');
<activity android:name="xxx.CallbackActivity">
            <intent-filter>
                <action android:name="android.intent.action.SEND" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="zxing" android:host="scan" android:path="/"/>
            </intent-filter>
        </activity>
Its not working tried with other window provided methods as well. like replace.

2. I have 1 activity which is not exactly LauncherActivity from AndroidBrowserHelper but yeah it contains logic from LauncherActivity only from ABH to be a TWA. As a limitation i need to use Azure auth only.

**Comment by andreban** [comment]
The solution to this would be an approach similar to what's documented in [this blogpost]. Steps 3 and 4 are the most relevant.
