### ISSUE TITLE
Update compileSdkVersion for some demos

### ISSUE THREAD

**Issue by PEConn** [GoogleChrome/android-browser-helper#240]
compileSdkVersion in:
- [x] demos/twa-location-delegation/build.gradle
- [x] demos/custom-tabs-example-app/build.gradle

Is 29, we should update it to 30.

**Comment by andreban** [comment]
`demos/custom-tab-example/app/build.gradle` was updated in #300.

**Comment by andreban** [comment]
`demos/twa-location-delegation/build.gradle` updated via #301
