### ISSUE TITLE
Clear cookies of TWA web view

### ISSUE THREAD

**Issue by mohit1993** [GoogleChrome/android-browser-helper#241]
I know it is not possible for custom tabs to clear cookies but for web view it is possible.
Is there any way to clear cookies programmatically  for TWA?

**Comment by PEConn** [comment]
Not really - TWAs share state with the user's default browser, so a TWA clearing cookies would mean clearing the all of user's cookies.

**Comment by andreban** [comment]
Also, Trusted Web Activity can be seen as a Custom Tabs without the address bar. So, most of the expectations around CustomT abs are also valid for TWAs.
