### ISSUE TITLE
Handle whitescreen after splash screen removed 

### ISSUE THREAD

**Issue by mohit1993** [GoogleChrome/android-browser-helper#248]
Hi All,

I am showing splash screen(TWA splash) when launching TWA, but i see white screen for 4-5 seconds after splash screen when launch app after a delay, as my web code needs to load a lot more data before launch, i know my web code should not take too much time to load, but i want to handle this white screen with a loader on native end only due to some limitation.
I have not extended LauncherActivity neither used it as launcher in Manifest, i had copied code(what ever required) from this activity to my native activity Abc due to some conditional launch.
I am not able to figure out which activity is hosting web content now after TWA launch. As my activity Abc seems to be in onPause state. so i can not use this activity to show loader. I f i used a new activity to show a loader my web content does not load in background, it starts loading only when web content is in foreground.
I want to show loader when there is time to load web content, is there any way to do it?

Note: i have few redirects in my web urls for launch.

**Comment by andreban** [comment]
The splash screen provided by the TWA will go away according to the progress on the page load - IIRC, when DOMContentLoaded is fired, but this may not be exact.

From your description, it looks like the web app is showing performance issues, and that's what needs to be improved. Start by making sure that the `startUrl` is the final URL and avoid any redirects. Check out https://web.dev/fast/ for more tips on performance.

As a reminder, we strongly recommend a Lighthouse performance score equal or larger than 80. You can use https://web.dev/measure/ to check the web app's performance.
