### ISSUE TITLE
Change browser preference for TWA

### ISSUE THREAD

**Issue by mohit1993** [GoogleChrome/android-browser-helper#253]
Is there any way to alter browser preferences for twa, i want to open edge if it installed over chrome.

**Comment by andreban** [comment]
The recommendation and what is implemented in `android-browser-helper` is to give priority to the user's default browser if it supports Trusted Web Activity. If the user doesn't have a default browsers, there's no specific order and the first browser that supports Trusted Web Activity returned by PackageManager will be used. You can check out the logic in [TwaProviderPicker](https://github.com/GoogleChrome/android-browser-helper/blob/master/androidbrowserhelper/src/main/java/com/google/androidbrowserhelper/trusted/TwaProviderPicker.java)

It's possible to launch the Trusted Web Activity with a specific package and you can check [LauncherActivity](https://github.com/GoogleChrome/android-browser-helper/blob/master/androidbrowserhelper/src/main/java/com/google/androidbrowserhelper/trusted/LauncherActivity.java) and [TwaLauncher](https://github.com/GoogleChrome/android-browser-helper/blob/master/androidbrowserhelper/src/main/java/com/google/androidbrowserhelper/trusted/TwaLauncher.java) for details. 

Having said that, we do recommend respecting the user's browser choice. Curious on why this doesn't look like the case for your app.

**Comment by andreban** [comment]
Closing as the question has been answered.
