### ISSUE TITLE
[Ask-Confirm] Do i need get approval for accessing location in the background 

### ISSUE THREAD

**Issue by thanhtungka91** [GoogleChrome/android-browser-helper#254]
Our TWA app is running on Chrome Custom Tab, if Chrome is accessing locations in the background, Do we need to get approval from google?

**Comment by PEConn** [comment]
I don't believe Chrome will allow you to access locations in the background, only when the app is in the foreground.

What type of approval from Google were you thinking of?

**Comment by thanhtungka91** [comment]
thank you for the answer, we got the message from google that one of our apps is accessing the location in the background and we need to get approval from google otherwise the app will be removed from the play store, but I am not sure whether our TWA app is accessing the location in the background or not. 

As you answer, I think now there is no problem with our TWA app.

**Comment by andreban** [comment]
@thanhtungka91 the web application itself won't have access to background location, as there's no browser API for that. Was code that access location in the background added to the Android part of the application?

**Comment by andreban** [comment]
Closing this issue, as it's not related to android-browser-helper. Please, re-open if this isn't the case.
