### ISSUE TITLE
POM file for billing v1.0.0-alpha06 has broken dependency

### ISSUE THREAD

**Issue by rwolski** [GoogleChrome/android-browser-helper#267]
The latest version of the androidbrowserhelper.billing package seems to have in invalid dependency which cannot be resolved by gradle. The package is available at https://maven.google.com/web/index.html?q=#com.google.androidbrowserhelper:billing:1.0.0-alpha06.

**To Reproduce**
1. Change the version of the dependency 'com.google.androidbrowserhelper:billing' from alpha05 to alpha06
2. Run bubblewrap update
3. Observe gradle error

**Expected behavior**
A successful build with the latest package

**Did this ever used to work**
Billing v1.0.0-Alpha05 worked correctly but a new dependency seems to have snuck into the Alpha06 pom file. I'm not sure if there's meant to be a new dependency or not. 

**Workaround**
The following seems to be a workaround for now as it excludes the broken dependency and build correctly. I'm not sure if this will have side effects though.

```
implementation('com.google.androidbrowserhelper:billing:1.0.0-alpha06') {
        exclude group: 'android-browser-helper', module: 'androidbrowserhelper'
}
```

**Screenshots**
![image](https://user-images.githubusercontent.com/4254290/109738119-f82ebc00-7c12-11eb-8980-9b456967755b.png)

**Comment by andreban** [comment]
This has been fixed. Closing the issue.
