### ISSUE TITLE
Set headers doesn't work in CustomTabsIntent

### ISSUE THREAD

**Issue by Arman-Hosseini** [GoogleChrome/android-browser-helper#269]
**Summary**
Hello. This issue is not about this repo, and I do not know where the appropriate repository is to raise this issue.
Please forgive me if I am in the wrong place and if you can guide me.

I use this code to send a Authorization header and it works in older browsers, but it doesn't work in newer browsers. Is there a way to send the header???
I also posted this issue on stackoverflow but did not receive a response. 

    CustomTabsIntent.Builder builder = new CustomTabsIntent.Builder();
    CustomTabsIntent customTabsIntent = builder.build();

    Bundle headers = new Bundle();
    headers.putString("Authorization", ApiKey.getToken());
    customTabsIntent.intent.putExtra(Browser.EXTRA_HEADERS, headers);
    customTabsIntent.launchUrl(this, Uri.parse(url));

**Comment by andreban** [comment]
Please, check out this [StackOverflow answer](https://stackoverflow.com/questions/62682574/android-params-inside-bundle-using-extra-headers-through-customtabs-intent-ar). This [document](https://developer.chrome.com/docs/android/custom-tabs/headers/) explain which headers are always OK and how to sending custom non-CORS headers.
