### ISSUE TITLE
Update "SVG OMG" demo site and docs to point to latest version

### ISSUE THREAD

**Issue by demianrenzulli** [GoogleChrome/android-browser-helper#270]
**Describe the bug**

This is not a bug but two requests for updates in demos and docs:

- Some demos, for example [twa-firebase-analytics](https://github.com/GoogleChrome/android-browser-helper/tree/main/demos/twa-firebase-analytics) are using an old demo site, that's currently down: https://svgomg.firebaseapp.com/.

- The [integration guide](https://developer.chrome.com/docs/android/trusted-web-activity/integration-guide/) still points to the previous version of Android Browser Helper (2.1.0). The current one ([2.2.0](https://github.com/GoogleChrome/android-browser-helper/releases/tag/androidbrowserhelper-2.2.0)) contains some useful hooks for developers (e.g. `launchTWA()`), so maybe it's good to update the guide if the latest is a stable version.

cc // @andreban

**Comment by andreban** [comment]
#271 replaces svgomg with Airhorner on the samples.

**Comment by andreban** [comment]
Docs have been updated air demos changed to Airhorner, so we can close this.
