### ISSUE TITLE
Overriding shouldLaunchImmediately() on the first TWA's launch could have an unexpected behavior

### ISSUE THREAD

**Issue by enricofacchinetti** [GoogleChrome/android-browser-helper#281]
Hi, here are the complete details of an issue/bug concerning the override of the method shouldLaunchImmediately().
This issue could be a bug but I'm not sure.
I tried to strictly refer to the available documentation but I'm not sure where the error comes from.

**The goal to be achieved**
The purpose of the code below is to override the **shouldLaunchImmediately()** method in a class that extends the android-browser-helper's **LauncherActivity** to add a query string to the underlying web app url.
The need is also to render the TWA only after generating a new **Firebase Token** which is retrieved through the **addOnCompleteListener** event handler.

The steps are the following:
**1)** If this is the first time app is launched, I generate the firebase token in the following manner:
FirebaseMessaging.getInstance().GetToken().AddOnCompleteListener(task -> {....})

**2)** Once the token has been recovered, I interface via JsonObjectRequest to an api on a dedicated server. The Guid returned by the API's http POST request is assigned to a local variable declared in the class extending LauncherActivity.

**3)** Overriding **getLaunchingUrl()** checks that the Guid has been assigned to the local variable **fcm_my_server_installId**.

**4)** If the variable fcm_my_server_installId has been set, the Guid is added to the url as a querystring in the following form:
https://myapp/home?installationId=guid-value
 
**5)** If the variable has not been set, this is not the first launch of the app. In that case, **shouldLaunchImmediately()** method returns "true" and **getLaunchingUrl()** returns the url with no query string.

**Describe the bug**
- Sometimes the following code:
String token = task.getResult();
throws com.google.android.gms.tasks.RuntimeExecutionException exception (Service Unavailable), but not always.
 (With the Pixel 3 XL virtual device it happened).
- App splash screen gets stuck on screen indefinitely (Always happens)
- Starting from the second loading (without query string) the app loads correctly (It always happens).
- If (keeping the same code) I only remove the override of **shouldLaunchImmediately()** method by restoring the default behavior of the TWA, the app is generally loaded correctly both the first time and the following ones, but the method overriding **getLaunchingUrl()** is launched twice and two instances of the app are loaded on the virtual device screen.

 
**Code Snippets**

```java
package ...;
import ...

public class CustomTwaActivity extends LauncherActivity {

    private String fcm_my_server_installId;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

	    boolean bGetNewToken = check_If_Get_New_FCMToken();
        if (bGetNewToken) {
            set_Firebase_New_Token();
        }	
    }

    @Override
    protected boolean shouldLaunchImmediately() {
        // if shouldLaunchImmediately() returns 'false' we want to wait until we got a new Firebase token
        // and then launch the Trusted Web Activity with 'launchTwa()'.
        boolean bGetNewToken = check_If_Get_New_FCMToken();
        return !bGetNewToken;
    }

    private boolean check_If_Get_New_FCMToken()
    {
      return (Is It the first load?);
    }

    private void set_Firebase_New_Token() {
        try {
            FirebaseMessaging firebaseMessaging = FirebaseMessaging.getInstance();
            // Start the asynchronous task to get a new Firebase Token.
            firebaseMessaging.getToken().addOnCompleteListener(task -> {
                try {					
                    // Once the task is complete, use token to get my server installId 
                    // and use it in the method getLaunchingUrl().
                    String token = task.getResult();
                    set_local_fcm_installId_from_my_server(getApplicationContext(), token);
					
                } catch (com.google.android.gms.tasks.RuntimeExecutionException ex) {
                    launchTwa();
                }
            });
        } catch (Exception e) {
            Log.e(TAG, getString(R.string.FailToReg_FCMtoken), e);
        }
    }

    private void set_local_fcm_installId_from_my_server(Context context, String token) {
        try {
            JSONObject jsonRequest = new JSONObject();
            jsonRequest.put("inputFieldName", token);
            RequestQueue queue = Volley.newRequestQueue(context);

            JsonObjectRequest jsonObjectRequest = new JsonObjectRequest
                    (Request.Method.POST, "https://my-remote-api", jsonRequest,
                            response -> {
                                try {
                                    if (response == null) { return; }
                                    fcm_my_server_installId = response.getString("outputFieldName")
                                } finally {
                                    queue.stop();
                                    launchTwa();
                                }
                            },
                            error -> {
                                Throwable cause = error.getCause();
                                String msg = error.getLocalizedMessage();
                                if (cause != null) {
                                    msg = (msg == null) ? "Unknown error" : msg;
                                    Log.println(Log.ERROR, cause.getMessage(), msg);
                                }
                                queue.stop();
                            }
                    );
            // Add the request to the RequestQueue.
            queue.add(jsonObjectRequest);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
	
    @Override
    protected Uri getLaunchingUrl() {
        Uri uri = super.getLaunchingUrl();
        Uri resultUri;
        if (fcm_my_server_installId != null) {
            resultUri = uri.buildUpon()
                    .appendQueryParameter("installationId", fcm_my_server_installId)
                    .build();
        } else {
            resultUri = uri;
        }
        return resultUri;
    }

}

```

**To Reproduce**
Launch the code through one of the default virtual devices of Visual Studio Code.

**Expected behavior**
Twa is correctly loaded both the first time (with the query string set) and the following ones (without any query string set)

**Smartphones**
 - Device: All the default virtual devices installed in Visual Studio Code (Pixel 3 XL, 4.7WXGA, Galaxy Nexus...)
 - OS: Android 10
 - Browsers Installed: Chrome
 - Browser Versions: 83
 - android-browser-helper library version: 2.2.0

**Comment by enricofacchinetti** [comment]
Hi, would like to better describe the bug to be more clear. Sorry for the lack of clarity.

- TWA's splash screen always gets stuck indefinitely, but only during the first load of the app, that is, when FCM token is generated and the custom installation id is added to the url as query string.
- Starting from the second load the app always loads correctly.
- If (keeping the same code) I only remove the override of **shouldLaunchImmediately()** method by restoring the default behavior of the TWA, the app is generally loaded correctly both the first time and the following ones. However, in that case (but only on the first load) the method overriding **getLaunchingUrl()** is launched twice and two instances of the app are loaded on the virtual device screen.
- And finally, sometimes the following code:
String token = task.getResult();
throws com.google.android.gms.tasks.RuntimeExecutionException exception (Service Unavailable), but not always.
(With the Pixel 3 XL virtual device it happened).

**Comment by maddumarala** [comment]
Any feedback on this ? 
I'm facing the same problem. Is it happen only on virtual devices  @enricofacchinetti ?

**Comment by enricofacchinetti** [comment]
Maybe the problem comes from the event onNewToken() of FirebaseMessagingService that is not properly handled in this scenario. Properly handling this event, the problem disappears though most of the times, when the event is fired, the app has been already loaded. Now, I patched the problem saving my installation id in shared preferences in onNewToken() method override. Once the installation id is in the shared preferences, it is added to the query string the following time the app is launched. I'm pretty much obliged to send my Id to the web app, on the second load of the app. Il 19 apr 2021 11:20 AM, maddumarala ***@***.***> ha scritto:
Any feedback on this ?
I'm facing the same problem. Is it happen only on virtual devices  @enricofacchinetti ?

**Comment by maddumarala** [comment]
Second time loading always works , since the token is already generated by then.
Still not found a workaround with first loading splash screen

**Comment by maddumarala** [comment]
@PEConn @andreban  Any help would be greatly appreciated.

**Comment by PEConn** [comment]
Heya,

I had a look through your code and I can't see anything obviously wrong. My next step would be to add some log statement to every single code block (method, callback, branch of an if statement) and follow the code through on the first run case.

We basically want to make sure that launchTwa has been called on the first run, and check if not, why.

**Comment by paulsharratt0** [comment]
I'm also experiencing this issue, and can confirm launchTwa is being called on the first run, we get this in the debug

2021-06-04 15:52:31.059 17547-17547/au.com.xxxxx D/TwaLauncher: Launching Trusted Web Activity.

but it does not progress past this step.  OP has a workaround listed here https://stackoverflow.com/questions/67390311/firebase-token-in-url which i'm going to try.

**Comment by andreban** [comment]
It turns out the problem here is that, when the delay between starting the Activity and launching the TWA is larger than ~200ms, [this callback](https://github.com/GoogleChrome/android-browser-helper/blob/main/androidbrowserhelper/src/main/java/com/google/androidbrowserhelper/trusted/LauncherActivity.java#L323-L329) is triggered before `mSplashScreenStrategy` is created, so the Splash never knows that the animation is finished and the splash screen is never removed.

We'll look into fixing that in the library but, in the meantime, a workaround is to call `onEnterAnimationComplete()` on the Activity after calling `launchTwa()`. This may cause `onEnterAnimationComplete()` to be called twice but, looking at the [callback here](https://github.com/GoogleChrome/android-browser-helper/blob/main/androidbrowserhelper/src/main/java/com/google/androidbrowserhelper/trusted/splashscreens/PwaWrapperSplashScreenStrategy.java#L240-L246), it shouldn't have any side effects.

```java
public class MyLauncherActivity extends LauncherActivity {

    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        
        new Handler(Looper.getMainLooper()).postDelayed(() -> {
            launchTwa();
            onEnterAnimationComplete();
        },5000L);
    }

    @Override
    protected boolean shouldLaunchImmediately() {
        return false;
    }
}
```
