### ISSUE TITLE
Android Browser Helper 2.2.1 and Android Studio

### ISSUE THREAD

**Issue by MatWez** [GoogleChrome/android-browser-helper#304]
**Describe the bug**
Hello to all the community. We have a TWA application which is based on the android browser helper library.
I'm trying to get the latest version of the LauncherActivity.class file linked to the latest 2.2.1 release [https://github.com/GoogleChrome/android-browser-helper/blob/main/androidbrowserhelper/src/main/java/com /google/androidbrowserhelper/trusted/LauncherActivity.java](url)

Unfortunately the version that is loaded in Android Studio when I load in the AndroidManifest.xml: implementation
'com.google.androidbrowserhelper: androidbrowserhelper: 2.2.1' is not up to date.

Do any of you have a solution to this problem?

Thx a lot in advance for your responses.

**To Reproduce**
1. Go to '.Android Studio..'
2. Build with  'implementation com.google.androidbrowserhelper: androidbrowserhelper: 2.2.1' 
3. Go to 'ActivityLauncher.class' and compare with [https://github.com/GoogleChrome/android-browser-helper/blob/main/androidbrowserhelper/src/main/java/com /google/androidbrowserhelper/trusted/LauncherActivity.java](url)

**Comment by andreban** [comment]
Hey @MatWez, the `main` branch in the repository is the development branch. You probably want to compare the [`LauncherActivity`](https://github.com/GoogleChrome/android-browser-helper/blob/android-browser-helper-2.2.1/androidbrowserhelper/src/main/java/com/google/androidbrowserhelper/trusted/LauncherActivity.java) in the [`androidbrowserhelper-2.2.1`](https://github.com/GoogleChrome/android-browser-helper/tree/android-browser-helper-2.2.1) branch.

**Comment by MatWez** [comment]
Hi @andreban Thx for your response. 

Here my LauncherActivity.class in my android studio project : 

`//
// Source code recreated from a .class file by IntelliJ IDEA
// (powered by FernFlower decompiler)
//

package com.google.androidbrowserhelper.trusted;

import android.app.Activity;
import android.content.Intent;
import android.graphics.Matrix;
import android.net.Uri;
import android.os.Bundle;
import android.util.Log;
import android.widget.ImageView.ScaleType;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.browser.customtabs.CustomTabColorSchemeParams;
import androidx.browser.customtabs.CustomTabsCallback;
import androidx.browser.customtabs.CustomTabColorSchemeParams.Builder;
import androidx.browser.trusted.TrustedWebActivityDisplayMode;
import androidx.browser.trusted.TrustedWebActivityIntentBuilder;
import androidx.browser.trusted.sharing.ShareData;
import androidx.browser.trusted.sharing.ShareTarget;
import androidx.core.content.ContextCompat;
import com.google.androidbrowserhelper.trusted.TwaLauncher.FallbackStrategy;
import com.google.androidbrowserhelper.trusted.splashscreens.PwaWrapperSplashScreenStrategy;
import org.json.JSONException;

public class LauncherActivity extends Activity {
    private static final String TAG = "TWALauncherActivity";
    private static final String BROWSER_WAS_LAUNCHED_KEY = "android.support.customtabs.trusted.BROWSER_WAS_LAUNCHED_KEY";
    private static final String FALLBACK_TYPE_WEBVIEW = "webview";
    private static boolean sChromeVersionChecked;
    private LauncherActivityMetadata mMetadata;
    private boolean mBrowserWasLaunched;
    @Nullable
    private PwaWrapperSplashScreenStrategy mSplashScreenStrategy;
    private CustomTabsCallback mCustomTabsCallback = new QualityEnforcer();
    @Nullable
    private TwaLauncher mTwaLauncher;

    public LauncherActivity() {
    }

    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        if (this.restartInNewTask()) {
            this.finish();
        } else if (savedInstanceState != null && savedInstanceState.getBoolean("android.support.customtabs.trusted.BROWSER_WAS_LAUNCHED_KEY")) {
            this.finish();
        } else {
            if (this.shouldLaunchImmediately()) {
                this.launchTwa();
            }

        }
    }

    protected boolean shouldLaunchImmediately() {
        return true;
    }

    protected void launchTwa() {
        this.mMetadata = LauncherActivityMetadata.parse(this);
        if (this.splashScreenNeeded()) {
            this.mSplashScreenStrategy = new PwaWrapperSplashScreenStrategy(this, this.mMetadata.splashImageDrawableId, this.getColorCompat(this.mMetadata.splashScreenBackgroundColorId), this.getSplashImageScaleType(), this.getSplashImageTransformationMatrix(), this.mMetadata.splashScreenFadeOutDurationMillis, this.mMetadata.fileProviderAuthority);
        }

        CustomTabColorSchemeParams darkModeColorScheme = (new Builder()).setToolbarColor(this.getColorCompat(this.mMetadata.statusBarColorDarkId)).setNavigationBarColor(this.getColorCompat(this.mMetadata.navigationBarColorDarkId)).setNavigationBarDividerColor(this.getColorCompat(this.mMetadata.navigationBarDividerColorDarkId)).build();
        TrustedWebActivityIntentBuilder twaBuilder = (new TrustedWebActivityIntentBuilder(this.getLaunchingUrl())).setToolbarColor(this.getColorCompat(this.mMetadata.statusBarColorId)).setNavigationBarColor(this.getColorCompat(this.mMetadata.navigationBarColorId)).setNavigationBarDividerColor(this.getColorCompat(this.mMetadata.navigationBarDividerColorId)).setColorScheme(0).setColorSchemeParams(2, darkModeColorScheme).setDisplayMode(this.getDisplayMode()).setScreenOrientation(this.mMetadata.screenOrientation);
        if (this.mMetadata.additionalTrustedOrigins != null) {
            twaBuilder.setAdditionalTrustedOrigins(this.mMetadata.additionalTrustedOrigins);
        }

        this.addShareDataIfPresent(twaBuilder);
        this.mTwaLauncher = this.createTwaLauncher();
        this.mTwaLauncher.launch(twaBuilder, this.mCustomTabsCallback, this.mSplashScreenStrategy, () -> {
            this.mBrowserWasLaunched = true;
        }, this.getFallbackStrategy());
        if (!sChromeVersionChecked) {
            ChromeUpdatePrompt.promptIfNeeded(this, this.mTwaLauncher.getProviderPackage());
            sChromeVersionChecked = true;
        }

        if (ChromeOsSupport.isRunningOnArc(this.getApplicationContext().getPackageManager())) {
            (new TwaSharedPreferencesManager(this)).writeLastLaunchedProviderPackageName("org.chromium.arc.payment_app");
        } else {
            (new TwaSharedPreferencesManager(this)).writeLastLaunchedProviderPackageName(this.mTwaLauncher.getProviderPackage());
        }

        ManageDataLauncherActivity.addSiteSettingsShortcut(this, this.mTwaLauncher.getProviderPackage());
    }

    protected TwaLauncher createTwaLauncher() {
        return new TwaLauncher(this);
    }

    private boolean splashScreenNeeded() {
        return this.mMetadata.splashImageDrawableId == 0 ? false : this.isTaskRoot();
    }

    private void addShareDataIfPresent(TrustedWebActivityIntentBuilder twaBuilder) {
        ShareData shareData = SharingUtils.retrieveShareDataFromIntent(this.getIntent());
        if (shareData != null) {
            if (this.mMetadata.shareTarget == null) {
                Log.d("TWALauncherActivity", "Failed to share: share target not defined in the AndroidManifest");
            } else {
                try {
                    ShareTarget shareTarget = SharingUtils.parseShareTargetJson(this.mMetadata.shareTarget);
                    twaBuilder.setShareParams(shareTarget, shareData);
                } catch (JSONException var4) {
                    Log.d("TWALauncherActivity", "Failed to parse share target json: " + var4.toString());
                }

            }
        }
    }

    @NonNull
    protected ScaleType getSplashImageScaleType() {
        return ScaleType.CENTER;
    }

    @Nullable
    protected Matrix getSplashImageTransformationMatrix() {
        return null;
    }

    private int getColorCompat(int splashScreenBackgroundColorId) {
        return ContextCompat.getColor(this, splashScreenBackgroundColorId);
    }

    protected void onRestart() {
        super.onRestart();
        if (this.mBrowserWasLaunched) {
            this.finish();
        }

    }

    protected void onDestroy() {
        super.onDestroy();
        if (this.mTwaLauncher != null) {
            this.mTwaLauncher.destroy();
        }

        if (this.mSplashScreenStrategy != null) {
            this.mSplashScreenStrategy.destroy();
        }

    }

    protected void onSaveInstanceState(Bundle outState) {
        super.onSaveInstanceState(outState);
        outState.putBoolean("android.support.customtabs.trusted.BROWSER_WAS_LAUNCHED_KEY", this.mBrowserWasLaunched);
    }

    public void onEnterAnimationComplete() {
        super.onEnterAnimationComplete();
        if (this.mSplashScreenStrategy != null) {
            this.mSplashScreenStrategy.onActivityEnterAnimationComplete();
        }

    }

    protected Uri getLaunchingUrl() {
        Uri uri = this.getIntent().getData();
        if (uri != null) {
            Log.d("TWALauncherActivity", "Using URL from Intent (" + uri + ").");
            return uri;
        } else if (this.mMetadata.defaultUrl != null) {
            Log.d("TWALauncherActivity", "Using URL from Manifest (" + this.mMetadata.defaultUrl + ").");
            return Uri.parse(this.mMetadata.defaultUrl);
        } else {
            return Uri.parse("https://www.example.com/");
        }
    }

    protected FallbackStrategy getFallbackStrategy() {
        return "webview".equalsIgnoreCase(this.mMetadata.fallbackStrategyType) ? TwaLauncher.WEBVIEW_FALLBACK_STRATEGY : TwaLauncher.CCT_FALLBACK_STRATEGY;
    }

    protected TrustedWebActivityDisplayMode getDisplayMode() {
        return this.mMetadata.displayMode;
    }

    private boolean restartInNewTask() {
        boolean hasNewTask = (this.getIntent().getFlags() & 268435456) != 0;
        boolean hasNewDocument = (this.getIntent().getFlags() & 524288) != 0;
        if (hasNewTask && !hasNewDocument) {
            return false;
        } else {
            Intent newIntent = new Intent(this.getIntent());
            int flags = this.getIntent().getFlags();
            flags |= 268435456;
            flags &= -524289;
            newIntent.setFlags(flags);
            this.startActivity(newIntent);
            return true;
        }
    }
}
`

**Comment by andreban** [comment]
> Source code recreated from a .class file by IntelliJ IDEA (powered by FernFlower decompiler)

If you are using a decompiler, the code should probably be semantically the same (ie: will do the same thing), but won't be exactly the same . Is there a specific part of the code you are looking for?

**Comment by MatWez** [comment]
Yes i'm looking for the fix with isFinish Function in LaunchTwa Function

**Comment by MatWez** [comment]
Problem Solve with android-browser-helper2.2.2

Thx a lot @andreban ;)
