### ISSUE TITLE
Support subscription price changes in the Play Billing library.

### ISSUE THREAD

**Issue by PEConn** [GoogleChrome/android-browser-helper#316]
Allow apps to launch the [Price Change Confirmation Flow](https://developer.android.com/google/play/billing/subscriptions#price-change-launch) by adding a flag in the payment request data, eg:

```
    const supportedInstruments = [{
        supportedMethods: 'https://play.google.com/billing',
        data: {
            sku: "my.sku.here",
            priceChangeConfirmation: "true"
        }
    }]
```

The code change itself will be broken down into the following parts:

- [x] Allow this field to be read into MethodData.
- [x] Create a new PaymentResult type to return.
- [x] Add launchPriceChangeConfirmationFlow to the BillingWrapper and subclasses.
- [x] Wire everything up.
- [x] Add instrumentation tests.

**Comment by PEConn** [comment]
All the code changes have landed, over to @andreban to put it in the next release.

**Comment by andreban** [comment]
Do we need a core release too? Or just billing?

**Comment by PEConn** [comment]
I've not touched anything in core, we just need a billing release.

**Comment by andreban** [comment]
Cool - release is ready, just waiting for approval.

**Comment by PEConn** [comment]
Approved (sorry, I was having some trouble with authenticating yesterday).

**Comment by rsolomakhin** [comment]
Is this OK to close as "fixed"?

**Comment by PEConn** [comment]
Sure.
