### ISSUE TITLE
Android version support confirmation. 

### ISSUE THREAD

**Issue by thanhtungka91** [GoogleChrome/android-browser-helper#33]
As the demo package, the minsdk is 23 it means that TWA will only support android from  6.0?

As the [TWA document](https://developers.google.com/web/updates/2019/02/using-twa), the mindsdk is 16 (from android 4.1) but it also mentioned that only support Chrome version 72 later. 
As I know chrome 72 only supports android from 4.4  So could you please confirm what is the minsdk will support TWA?

Thanks.

**Comment by PEConn** [comment]
The minSdk for the demos is irrelevant to TWAs - I think it was just what Android Studio had as default when we created the demos.

The androidbrowserhelper library and AndroidX.Browser (which we rely on) have a minSdkVersion of 16, meaning that you can build your app for Android 4.1 (Jellybean).

You are right that Chrome 72 is only available on Android 4.4 (KitKat) or above. This means that if you deploy your TWA on Android Jellybean:
* Maybe the user has a non-Chrome browser installed that supports TWAs (though I don't know of any that do at the moment).
* Your app would still run, but it would do so as a Custom Tab, not a TWA.

Alternatively if you had some other fallback in place (eg, launching the webpage in a WebView if there are no TWA supporting browsers), you could use that on Jellybean.

So, you can build and deploy your app to Android Jellybean, but it is likely that it would use the Custom Tabs fallback.

**Comment by thanhtungka91** [comment]
thank you for the classification, our app only support TWA with chrome and we don't want to fallback to webview at the moment, so we will set minsdk is 19 which support later 4.4 

thank you for the prompt response. I would like to close the ticket here.

**Comment by PEConn** [comment]
Glad I could help!
