### ISSUE TITLE
Hiding NavBar and StatusBar

### ISSUE THREAD

**Issue by n-belokopytov** [GoogleChrome/android-browser-helper#35]
It seems like NavBar and StatusBar can only change color with the existing functionality, while the installed PWA app is able to be truly full-screen. Am I missing something or is it a bug?

**Comment by pshmakov** [comment]
That's correct, the full-screen mode in TWAs is coming soon.

**Comment by andreban** [comment]
Work on the Chromium side is being tracked on this bug: https://bugs.chromium.org/p/chromium/issues/detail?id=965329

**Comment by PEConn** [comment]
I think this should by fixed by Issue #95

**Comment by andreban** [comment]
Work on the Chrome side is finished and this has been implemented in the library. Final implementations via #95.
