### ISSUE TITLE
mutiple hostname (subdomain) AssetLink verification failed after aab playstore rel ( fallback to customtabs )

### ISSUE THREAD

**Issue by govi2010** [GoogleChrome/android-browser-helper#376]
I have a TWA app for web URL https://domainname.com which is a multi-tenant market place and all tenant has a website with a different subdomain like https://xyz.domainName.com.

I have checked the below checklist

attach the google signing SHA256 key in both assetlinks.json.
Both are accessible and no 301 redirections occurred
try by clearing the chrome data also uninstall the app
check the key twice
In My case, the application can verify the https://domainname.com but can't verify https://xyz.domainName.com. so showing navigation bar when we navigate to any tenant site (https://xyz.domainName.com)

My app is working fine with the signed apk (both https://domainname.com and https://xyz.domainName.com are verified successfully) but when I upload the aab file to the play store for internal testing and downloaded from the store then https://xyz.domainName.com seems not verified successfully.

I also verified with the verification tool
https://developers.google.com/digital-asset-links/tools/generator

all looks fine there.

**Comment by PEConn** [comment]
Have you followed the [instructions in the twa-multi-domain](https://github.com/GoogleChrome/android-browser-helper/tree/main/demos/twa-multi-domain) demo?

**Comment by govi2010** [comment]
@PEConn  now it is working I need to create my app data from chrome which was having cached file.
