### ISSUE TITLE
restart app after updating a new version

### ISSUE THREAD

**Issue by thanhtungka91** [GoogleChrome/android-browser-helper#40]
I have raised the issue in [stackoverflow](https://stackoverflow.com/questions/59042768/restart-app-after-updating-a-new-version-in-chrome-custom-tab) 

Actually, I have raised the question in this thread But the issue seems can be resolved if users are using the native activity, the app will be restarted then they update a new version.

I am running the app with a custom tab, during the running the app (chrome on custom tab), then I use ADB to install a new version. In this case, maybe the new URL can be updated with a new value, I want to force users to restart the mainActivity with a new URL. However, as I see the users still use the old version (old URL) without any change until they restart the app.

Any way to force users to restart the app with new URL value?

I have tried Broadcast Reciever with "MY_PACKAGE_REPLACED" but it didn't help. 

Thanks.

**Comment by PEConn** [comment]
Hey,

I'm able to reproduce this issue on Android 10, but things work fine on Android Marshmallow. What version of Android are you running?

**Comment by thanhtungka91** [comment]
@PEConn 
It is android 9 in my case.

**Comment by PEConn** [comment]
This is a bug in Chrome.

I'd originally filed an Android bug, but nothing was happening on there and the bug wasn't public. I've moved it to Chromium's bug tracker now ([1046315](https://bugs.chromium.org/p/chromium/issues/detail?id=1046315)).

**Comment by andreban** [comment]
Closing this in favour of the Chromium bug.
