### ISSUE TITLE
Support setMediaPlaybackRequiresUserGesture webview setting

### ISSUE THREAD

**Issue by patrickhuijten** [GoogleChrome/android-browser-helper#413]
**Is your feature request related to a problem? Please describe.**
I created an issue on https://github.com/GoogleChromeLabs/bubblewrap/issues/767 about adding support for a setting of webview: `setMediaPlaybackRequiresUserGesture`. I got redirected to this repository by @andreban. Is this something that Android Browser Helper could help support?

**Describe the solution you'd like**
Support for enabling `setMediaPlaybackRequiresUserGesture` on webview settings.

**Describe alternatives you've considered**
N/A

**Additional context**
See https://github.com/GoogleChromeLabs/bubblewrap/issues/767  for additional context.

**Comment by patrickhuijten** [comment]
Any indication when I can expect a new release? @PEConn

**Comment by PEConn** [comment]
Hey, sorry for the delay, version 2.5.0 just got released and should include this change.

**Comment by patrickhuijten** [comment]
@PEConn Thank you for the update! Very excited about this 😄
