### ISSUE TITLE
Bump the `com.google.android.gms:play-services-location` version in `locationdelegation`

### ISSUE THREAD

**Issue by andreban** [GoogleChrome/android-browser-helper#433]
`com.google.android.gms:play-services-location`, used by the Location Delegation feature, includes a a transient dependency to `androidx.fragment` (via `play-services-base`), which is causing the Play Store to create a warning for applications using `android-browser-helper` + `locationdelegation` saying they are using an outdated SDK. See https://github.com/GoogleChromeLabs/bubblewrap/issues/810 for details.

Bumping the `play-services-location` in `locationdelegation` to the latest version should fix the issue.

**Comment by SharmaDhruv2511** [comment]
I just have to change the location to change the issue?
