### ISSUE TITLE
Cannot repro the demo of twa post message

### ISSUE THREAD

**Issue by ALiangLiang** [GoogleChrome/android-browser-helper#439]
**Read this First**
If you have a Trusted Web Activity related question, the best place to ask it is on StackOverflow, on the
[trusted-web-activity](https://stackoverflow.com/questions/tagged/trusted-web-activity) tag, which is also monitored by the team.

**Describe the bug**

I'm not sure it's a bug or not. I can't repro the demo.
I can compile it but cannot works correctly.

1. If I compile and open it directly. Cannot trigger `CustomTabsCallback`.
2. So I call `validateRelationship` after [`mSession = mClient.newSession(customTabsCallback);`](https://github.com/GoogleChrome/android-browser-helper/blob/4f43bbfc802b963d2e924577e460a216a01d9700/demos/twa-post-message/src/main/java/com/google/androidbrowserhelper/demos/twapostmessage/MainActivity.java#L141). But [`requestPostMessageChannel`](https://github.com/GoogleChrome/android-browser-helper/blob/4f43bbfc802b963d2e924577e460a216a01d9700/demos/twa-post-message/src/main/java/com/google/androidbrowserhelper/demos/twapostmessage/MainActivity.java#L113-L115) return `false`. I'm sure I've put `PostMessageService` in `AndroidManifest.xml`.

**To Reproduce**
1. Clone the repo
1. `cd android-browser-helper/demos/twa-post-message`
1. edit `MainActivity.java`. Replace `URL` and `TARGET_ORIGIN` by localhost site my owned. The site I already has assetlink.json which has correct sha256 of debug keystore and relation. And add following code at [line 142](https://github.com/GoogleChrome/android-browser-helper/blob/4f43bbfc802b963d2e924577e460a216a01d9700/demos/twa-post-message/src/main/java/com/google/androidbrowserhelper/demos/twapostmessage/MainActivity.java#L142). (already imported `CustomTabsService`)
    ```java
                            mSession.validateRelationship(CustomTabsService.RELATION_USE_AS_ORIGIN,
                                    TARGET_ORIGIN, new Bundle());
    ```
1. `adb logcat | grep PostMessageDemo`
1. `../../gradlew installDebug` and open the app by hands.
1. Following partial logs:
    ```
    08-08 00:53:20.868 25893 25893 D PostMessageDemo: Relationship result: true
    08-08 00:53:23.168 25893 25893 D PostMessageDemo: Requested Post Message Channel: false
    ```

**Expected behavior**

[`requestPostMessageChannel`](https://github.com/GoogleChrome/android-browser-helper/blob/4f43bbfc802b963d2e924577e460a216a01d9700/demos/twa-post-message/src/main/java/com/google/androidbrowserhelper/demos/twapostmessage/MainActivity.java#L113-L115) return `false` should return `true`

**Did this ever used to work**

no

**Screenshots**

**Code Snippets**
If applicable, add or link to code snippets describing how the API is being used.

**Smartphone (please complete the following information):**
 - Device: Pixel 5
 - OS: Android 13
 - Browsers Installed Chrome 115.0.5790.139 and Chrome Beta 116.0.5845.61 (Changed default broweser)
 - Browser Versions Chrome 115.0.5790.139 and Chrome Beta 116.0.5845.61 (Changed default broweser)
 - android-browser-helper library version 2.4.0

**Additional context**

**Comment by SayedElabady** [comment]
Thanks for reporting this, may I know the value of `SOURCE_ORIGIN` you are using?

**Comment by SayedElabady** [comment]
So that wasn't mentioned in the demo but the `SOURCE_ORIGIN` has to either start with http:// or https://, please try it and let me know if the issue still persists.

**Comment by ALiangLiang** [comment]
> So that wasn't mentioned in the demo but the `SOURCE_ORIGIN` has to either start with http:// or https://, please try it and let me know if the issue still persists.

I follow the [comment](https://github.com/GoogleChrome/android-browser-helper/blob/4f43bbfc802b963d2e924577e460a216a01d9700/demos/twa-post-message/src/main/java/com/google/androidbrowserhelper/demos/twapostmessage/MainActivity.java#L59). So I leave it as "my-app-origin-uri".
I just tried to changing it to "https://foo.bar" and it seems to work.

**Comment by SayedElabady** [comment]
Thanks for the confirmation.
