### ISSUE TITLE
[Ask] Is pre-render content still supported?

### ISSUE THREAD

**Issue by thanhtungka91** [GoogleChrome/android-browser-helper#44]
May I know the feature pre-render-content below is still supported in the android browser helper?
if yes, could you please share with us how to implement it?

https://developer.chrome.com/multidevice/android/customtabs#pre-render-content

We have a scenario like that: 
1. Run the TWA app with a specific link 
2. From TWA activity, we use deep-link to open another native activity 
3. From Activity, we do some tasks and depend on results we will return back TWA with new URL 
However when back to TWA with a new URL, there is still delay time which still shows previous page with the old URL before direct TWA to new URL. 
So I would like to know if we can pre-render or some tricks to open new TWA without showing the previous page?

Thank you in advance.

**Comment by PEConn** [comment]
Hey,

At the moment we don't have anything like what you're asking sorry. Pre-render content is supported, however that's the use case of starting a page load before the Custom Tab is launched, it sounds like in this case you're wanting to trigger a page load in an already launched Custom Tab before returning to it.

What kind of page load delay are you seeing? Is this something that could be sped up with website optimizations/service workers? Other than that, maybe you could finesse this slightly by providing a finish animation to your native Activity.
