### ISSUE TITLE
OK to subclass DelegationService?

### ISSUE THREAD

**Issue by alastaircoote** [GoogleChrome/android-browser-helper#62]
I'm evaluating how we might use android-browser-helper in our app. In an ideal world we'd be able to use more notification functionality than the web currently provides, so I started poking around.

I just did a quick test subclassing `DelegationService` and changing the service in the manifest XML to point to my subclass... and it works! But I wanted to check whether this is something you want people to be doing with the library and something that would be supported down the line?

**Comment by andreban** [comment]
Hi @alastaircoote 

It's totally fine to subclass DelegationService, and the class was designed to be extended. 

Andre
