### ISSUE TITLE
forceFallbackStrategy

### ISSUE THREAD

**Issue by alex2844** [GoogleChrome/android-browser-helper#65]
[google translate]
Not enough forceFallbackStrategy

For example, if the application is running on the Android TV platform and some browser is installed on it, then pwa is currently running in this browser, and I want getFallbackStrategy to be executed for the Android TV platform and run in webview.

To do this, I have to copy all the code from LauncherActivity and do a check at the beginning
getPackageManager().hasSystemFeature(PackageManager.FEATURE_LEANBACK)

[orig_ru]
Не хватает forceFallbackStrategy

Например, если приложение запущено на платформе андроид тв, и на нем установлен какой то браузер, то в данный момент pwa запускается в этом браузере, а я хочу чтоб в любом случае для платформы андроид тв выполнилось getFallbackStrategy и запустился во webview.

Для этого мне приходится копировать весь код из LauncherActivity и в начале делать проверку
getPackageManager().hasSystemFeature(PackageManager.FEATURE_LEANBACK)

**Comment by andreban** [comment]
Android TV doesn't come with a browser installed and Chrome doesn't have an Android TV version.

So, my expectation is that, if running on Android TV, it wouldn't find a browser that supports TWA and that would trigger a fallbackStrategy, without the need to force it.

Having said that, the default CCT strategy won't work (as there isn't usually a browser installed), and the developer would have to provide their own WebView fallback that is used to navigate both internal and external links (a modified version of this [demo](https://github.com/GoogleChrome/android-browser-helper/tree/master/demos/twa-webview-fallback)).

Can you provide:
  1. More details on the browser (or browsers) installed on the TV
  2. The configuration being used on AndroidManifest, build.gradle or any other classes used on the Android implementation.

**Comment by alex2844** [comment]
[google translate]
that's right, after installing the application on android tv, webview started, but when I was wondering if the browser is installed, how the application behaves, I installed chrome on android tv, and it’s not displayed in the webview, but chrome

1.chrome beta 80.0.3987.78
2. everything is like in the demo twa-webview-fallback

[orig_ru]
всё верно, после установки приложения на андроид тв запустился вебвью, но когда мне стало интересно если будет установлен браузер то как приложение себя поведет, установил я хром на андроид тв, и уже не в вебвью отображается, а хроме

1. хром бета 80.0.3987.78
2. всё как в демо twa-webview-fallback

**Comment by andreban** [comment]
How was Chrome installed into the Android TV?

**Comment by alex2844** [comment]
installing apk

**Comment by andreban** [comment]
Closing this, as supporting Android TV is not a goal at the moment.

**Comment by dseeker** [comment]
@andreban that's unfortunate, we have a multiscreen PWA that would benefit from this. 
If I read correctly we can still deploy the bubblewrap generated AAB/APK to android TV and it will fallback to webview, correct? as long as the PWA supports linear navigation it should work, or do we need to modify something in the manifest to make it work for Android TV?
