### ISSUE TITLE
Cannot make multi domain part to work

### ISSUE THREAD

**Issue by DanilaStrelkov** [GoogleChrome/android-browser-helper#69]
App in testing - https://play.google.com/apps/testing/ru.rambler.news
Starting domain - https://www.rambler.ru, additional domains are https://news.rambler.ru, https://sport.rambler.ru, etc (8 additional domains in total).
Done exactly as described in multi-domain demo (and readme), every domain has /.well-known/assetlinks.json exactly the same as starting domain. All required parts in strings.xml, AndroidManifest and build file are also done but still...
Starting domain verifies OK while all additional domains show blue url bar and act as unverified origins when user passes to them via the link on a starting page.

- Signing config matches sha256 in assetlinks.
- Build in Android Studio 3.5
- Last test performed with Chrome 80.0.3987.87 (still fail)

Files included in following archive:
[app_files.zip](https://github.com/GoogleChrome/android-browser-helper/files/4224943/app_files.zip)

**Comment by andreban** [comment]
I have reproduced the issue. android:value doesn't seem to be passed into the application metadata when the type is @array/*. #70 should fix this.

A small change will have to be made to the AndroidManifest.xml, replacing android:value with android:resource only for this particular meta-tag. The demo has been updated on #70 as well.

**Comment by DanilaStrelkov** [comment]
@andreban do I understand it correctly that I need to wait 'till 1.1.1 release for this fix to work? Thank you!

**Comment by andreban** [comment]
Yes, that's correct. We aim to release it next week. Sorry for the delay on that.

**Comment by DanilaStrelkov** [comment]
@andreban is there any chance it might happen soon? :)

**Comment by andreban** [comment]
Hi @DanilaStrelkov 

`com.google.androidbrowserhelper:androidbrowserhelper:1.2.0` is already out and should have this.

**Comment by DanilaStrelkov** [comment]
@andreban thanks! Will rebuild right now to check it. Somehow missed the release )
