### ISSUE TITLE
Add demos

### ISSUE THREAD

**Issue by PEConn** [GoogleChrome/android-browser-helper#8]
Add some examples to the demos module. Potentially copying from [custom-tabs-client](https://github.com/GoogleChrome/custom-tabs-client).

**Comment by PEConn** [comment]
And add docs to build them.

**Comment by andreban** [comment]
It seems it's worth renaming the demos folder to `demo` and having multiple modules inside it (eg: CCT, TWAs, etc). WDYT?

**Comment by andreban** [comment]
We have a `demos` folder with a couple of projects. We can create issues for more demos as needed. Closing this in favor of tracking specific demos
