### ISSUE TITLE
Can i send data from Android service and handle it in pwa ?

### ISSUE THREAD

**Issue by geminixandroid** [GoogleChrome/android-browser-helper#85]

**Comment by andreban** [comment]
@geminixandroid Currently, it's only possible to pass the from the native part of the App into the PWA at launch time. Here's how to do it with query parameters: https://developers.google.com/web/android/trusted-web-activity/query-parameters

PS: https://stackoverflow.com/questions/tagged/trusted-web-activity is the best place to ask questions related to Trusted Web Activity.
