### ISSUE TITLE
Links from Gmail mobile app are opening in micro-browser or crashing

### ISSUE THREAD

**Issue by mszklarski** [GoogleChrome/android-browser-helper#86]
**Describe the bug**
After recent update to last stable version of android-browser-helper we started to observe a bug across many devices that caused crashes or improper behavior that happens when people are opening specific links on the up-to-date Gmail mobile Android app. It is a problem only concerning this mobile mail client, it doesn't appear on Outlook mobile or other clients - there links are opening properly as TWA.

**To Reproduce**
1. Receive an e-mail on Gmail mobile app that contains a link to TWA-bundled app
2. Click on that link
3. Either website will be opened in Chrome micro-browser or it will crash at that point, it won't open it as TWA

**Expected behavior**
When TWA app is installed on device, such links should always open as existing or new TWA instance.

**Did this ever used to work**
Earlier android-browser-helper versions and Gmail mobile client app.

**Smartphone (please complete the following information):**
 - Device: OnePlus 7 Pro
 - OS: Android 10
 - Browsers Installed: Chrome
 - Browser Versions: latest
 - android-browser-helper library version: latest stable
 - Gmail Android client app version: latest stable

**Comment by andreban** [comment]
@mszklarski would you be able to capture the log for the crash with `adb logcat`?

**Comment by andreban** [comment]
@mszklarski after the e-mail conversation, can you confirm if you are still seeing this issue happening and it's not the same issue as #89?

**Comment by mszklarski** [comment]
Already fixed in 1.3.1-alpha01 ;)

**Comment by andreban** [comment]
`1.3.1` stable has been released.
